### ISSUE TITLE
is there a way to genetate ptyhon dictionary?

### ISSUE THREAD

**Issue by qtbgo** [ticdat/ticdat#126]
in my case,
print(dat.parameter) gives {1.0: _td:{'slotLength': 30.0, 'isUseRecommendGroup': 0.0}}

I wonder how to generate a python dictionary like 
myparameter = dat.copy_to_dictionary(dat.parametert), so that print(myparameter)

 gives  {1.0: {'slotLength': 30.0, 'isUseRecommendGroup': 0.0}}

In fact, what I really want is multidict in gurobipy. I wonder if this can be implemented efficiently in ticdat.

**Comment by pjcpjc** [comment]
@qtbgo  Sorry for delayed response. 
Here is a snippet from an ipython session based on [this](https://github.com/ticdat/ticdat/tree/master/examples/iris) example.

```
In [1]: import iris

In [2]: dat = iris.input_schema.csv.create_pan_dat("sample_data")
The following table names could not be found in the sample_data directory.
parameters

The following table names could not be found (or were empty).
parameters


In [3]: iris.input_schema.create_full_parameters_dict(dat)
Out[3]: {'Number of Clusters': 4}
``` 

This involves using the `add_parameter` functionality. It works the same for `TicDatFactory` and `PanDatFactory`. In this particular snippet, because the `"sample_data"` lacked a parameters.csv file, `dat.parameters` was empty and thus `create_full_parameters_dict` used the default value.  If I did something similar with the [metrorail](https://github.com/ticdat/ticdat/blob/master/examples/gurobipy/metrorail/metrorail.py) then the dictionary would have had two entries, one for `"One Way Price"` and one for `"Amount Leftover Constraint"`.

Feel free to join the ticdat slack at ticdat.slack.com. If you share an email address I can send you an invitation.  You don't have to share a full email, I can set things up so anyone with the same email domain can join. 

Or you can just keep asking questions like this, I just might not respond very quickly unless you ping me with @pjcpjc.

Reopen this ticket if you have any more questions.
