### ISSUE TITLE
how to freeze a single table?

### ISSUE THREAD

**Issue by qtbgo** [ticdat/ticdat#153]
Now, we can use freeze_me(dat) to freeze all tables included in the dat. I wonder if we can freeze a single table in the dat object?
for example freeze_me(dat.TableOne).

Thianks in advance.

**Comment by pjcpjc** [comment]
Sorry for delayed response @qtbgo. No way to freeze a single table. It's pretty easy to make a "smaller" object (i.e. make a `TicDatFactory` that only has a subset of the tables, and then make a frozen `TicDat` of the smaller-tables-TicDatFactory) but you'd still have either all the tables frozen or all the tables unfrozen. 

I found freezing a whole `TicDat` object helpful because the functionality [here](https://github.com/ticdat/ticdat/wiki/ticdat-defaultdict-enhancements) can sometimes cover up a mistake whereby I refer to a non-existent row and thus create the row. Thats behavior I want for creating a solution object, but not helpful for reading from an input object. So I often freeze the input object to make any "referring to rows that don't exist" bugs obvious. 

I found it helpful to freeze just one table, so never implemented it. If it comes up for me then I'll work on it. Closing this comment for now, however. 

Thanks for using ticdat.

**Comment by pjcpjc** [comment]
No worries @qtbgo glad you find it useful.

My thinking is that "unfreeze" should be impossible, because "freeze" converts the dat object into something that is immutable, like a tuple is immutable. Can you unfreeze a tuple and then add or reassign a member and then refreeze a tuple? No. But what you can do is copy the tuple to a list, then edit the list, then create a new tuple from the edited list. Thus, you can always invoke `copy_tic_dat` to get an unfrozen copy of the data, edit that copy, and then freeze the copy.
