### ISSUE TITLE
Future warnings popping up with more recent pandas

### ISSUE THREAD

**Issue by evpinheiro** [ticdat/ticdat#214]
We have a warning from pandas regarding deprecating the current 'read_json'. 

```
/.venv/lib/python3.11/site-packages/ticdat/pandatio.py:120: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
    rtn[t] = pd.read_json(json.dumps(loaded_dict[f]), orient=orient, **kwargs_)
```
The warning is

> FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version

It seems we can deal with it as recommended by the warning. I can make a pull request if you think it the right option.

**Comment by pjcpjc** [comment]
@evpinheiro Thanks for the update, but honestly, there are a bunch  like this because I'm swamped and I haven't brought `ticdat` up to date with latest `pandas`. I'm waiting for a customer to bug me to do this, or for someone else to volunteer to contribute to `ticdat` and work on it on a branch. Sorry if thats not what you want to hear, but it might be a little while before I get around to it.

Notes - fix for this is almost surely.

```
import io
```

and then

```
rtn[t] = pd.read_json(io.StringIO(json.dumps(loaded_dict[f])), orient=orient, **kwargs_)
```

But of course there are a bunch of others to worry about. I will need to run all the unit tests and clean out all the warnings. I also need to worry about a newer version of `sqlalchemy` at the same time as this upgrade, so its a bunch of stuff.

**Comment by pjcpjc** [comment]
@evpinheiro I know those warnings are irritating but honestly this is just things working as they should, IMHO. Some other `ticdat` person is more up to date than me, they give me the heads up, I get the fix out before there is a further `pandas` upgrade that breaks it. This is how I'd prefer to do it. So don't feel obligated to work on this unless you are really bothered by the warnings. If you find others you can just add them to this issue.

**Comment by pjcpjc** [comment]
Also need to fix this

```
FutureWarning: Starting with pandas version 3.0 all arguments of to_excel except for the argument 'excel_writer' will be keyword-only.
  getattr(pan_dat, t).to_excel \
```

Triggered by `pandatio.py`. 

```
        with pd.ExcelWriter(file_path) as writer:
            for t in self.pan_dat_factory.all_tables:
                getattr(pan_dat, t).to_excel \
                    (writer, (case_space_to_pretty(t) if case_space_sheet_names else t)[:_longest_sheet], index=False)
```

**Comment by pjcpjc** [comment]
Fix for all these now on develop.

**Comment by pjcpjc** [comment]
@evpinheiro 0.2.26 now on PyPi
